### ISSUE TITLE
Cannot dispatch action error when testing with turbine

### ISSUE THREAD

**Issue by JBokMan** [freeletics/FlowRedux#433]
Hi, we use the state machine in our code. And we test it with turbine. Unfortunately our tests fail sometimes. Because of that I created a minimal example to reproduce the error.

This is the error:
``` java

Cannot dispatch action com.example.util.MachineAction$TurnOn@615091b8 because state Flow of this FlowReduxStateMachine is not collected yet. Start collecting the state Flow before dispatching any action.
java.lang.IllegalStateException: Cannot dispatch action com.example.util.MachineAction$TurnOn@615091b8 because state Flow of this FlowReduxStateMachine is not collected yet. Start collecting the state Flow before dispatching any action.
at com.freeletics.flowredux.dsl.FlowReduxStateMachine.dispatch$suspendImpl(FlowReduxStateMachine.kt:74)
at com.freeletics.flowredux.dsl.FlowReduxStateMachine.dispatch(FlowReduxStateMachine.kt)
at com.example.util.StateMachineExample.on(ExampleTest.kt:45)
at com.example.util.ExampleTest$exampleTest$1$1$1.invokeSuspend(ExampleTest.kt:66)
at com.example.util.ExampleTest$exampleTest$1$1$1.invoke(ExampleTest.kt)
at com.example.util.ExampleTest$exampleTest$1$1$1.invoke(ExampleTest.kt)
at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:61)
at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
at app.cash.turbine.FlowKt.test-C2H2yOE(flow.kt:54)
at app.cash.turbine.FlowKt.test-C2H2yOE$default(flow.kt:49)
at com.example.util.ExampleTest$exampleTest$1.invokeSuspend(ExampleTest.kt:63)
(Coroutine boundary)
at com.example.util.ExampleTest$exampleTest$1.invokeSuspend(ExampleTest.kt:63)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invokeSuspend(TestBuilders.kt:212)
Caused by: java.lang.IllegalStateException: Cannot dispatch action com.example.util.MachineAction$TurnOn@615091b8 because state Flow of this FlowReduxStateMachine is not collected yet. Start collecting the state Flow before dispatching any action.
at com.freeletics.flowredux.dsl.FlowReduxStateMachine.dispatch$suspendImpl(FlowReduxStateMachine.kt:74)
at com.freeletics.flowredux.dsl.FlowReduxStateMachine.dispatch(FlowReduxStateMachine.kt)
at com.example.util.StateMachineExample.on(ExampleTest.kt:45)
at com.example.util.ExampleTest$exampleTest$1$1$1.invokeSuspend(ExampleTest.kt:66)
at com.example.util.ExampleTest$exampleTest$1$1$1.invoke(ExampleTest.kt)
at com.example.util.ExampleTest$exampleTest$1$1$1.invoke(ExampleTest.kt)
at app.cash.turbine.FlowKt$test$2.invokeSuspend(flow.kt:61)
at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
at app.cash.turbine.FlowKt$test$2.invoke(flow.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
at app.cash.turbine.FlowKt.test-C2H2yOE(flow.kt:54)
at app.cash.turbine.FlowKt.test-C2H2yOE$default(flow.kt:49)
at com.example.util.ExampleTest$exampleTest$1.invokeSuspend(ExampleTest.kt:63)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.selects.SelectBuilderImpl.resumeWith(Select.kt:300)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:28)
at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:100)
at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdleOr$kotlinx_coroutines_test(TestCoroutineScheduler.kt:120)
at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdle(TestCoroutineScheduler.kt:113)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:237)
at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$1.invokeSuspend(TestBuilders.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest$default(TestBuilders.kt:147)
at kotlinx.coroutines.test.TestBuildersKt.runTest$default(Unknown Source)
at com.example.util.ExampleTest.exampleTest(ExampleTest.kt:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

This is the minimal example:
``` kotlin
import app.cash.turbine.test
import com.freeletics.flowredux.dsl.FlowReduxStateMachine
import com.google.common.truth.Truth
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.FlowPreview
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.test.runTest
import org.junit.Test

sealed interface MachineState {
    object ON : MachineState
    object OFF : MachineState
}

sealed interface MachineAction {
    object TurnOn : MachineAction
    object TurnOff : MachineAction
}

@OptIn(ExperimentalCoroutinesApi::class, FlowPreview::class)
class StateMachineExample(initialState: MachineState = MachineState.OFF) :
    FlowReduxStateMachine<MachineState, MachineAction>(initialState) {
    init {
        spec {
            inState<MachineState.OFF> {
                on<MachineAction.TurnOn> { _, state ->
                    state.override { MachineState.ON }
                }
            }
            inState<MachineState.ON> {
                on<MachineAction.TurnOff> { _, state ->
                    state.override { MachineState.OFF }
                }
            }
        }
    }

    suspend fun on(action: MachineAction) {
        dispatch(action)
    }

    val stateFlow: StateFlow<MachineState> = state.stateIn(
        scope = CoroutineScope(Dispatchers.Default),
        started = SharingStarted.Eagerly,
        initialValue = initialState
    )
}

@OptIn(ExperimentalCoroutinesApi::class)
class ExampleTest {

    @Test
    fun exampleTest() = runTest {
        repeat(1000) {
            val sm = StateMachineExample()

            sm.stateFlow.test {
                Truth.assertThat(awaitItem()).isInstanceOf(MachineState.OFF::class.java)

                sm.on(MachineAction.TurnOn)

                Truth.assertThat(awaitItem()).isInstanceOf(MachineState.ON::class.java)
            }
        }
    }
}
```

These are the dependencies from the build.gradle.kts:
``` kotlin
dependencies {
    testImplementation(kotlin("test"))
    testImplementation("app.cash.turbine:turbine:0.12.1")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4")
    implementation("com.freeletics.flowredux:flowredux-jvm:1.0.2")
    implementation("com.freeletics.flowredux:compose:1.0.2")
    testImplementation("com.google.truth:truth:1.1.3")
}
```

Did we do something wrong?

**Comment by gabrielittner** [comment]
This is happening because of the general behavior of `StateFlow`. Since `StateFlow` has its own initial value that will get emitted immediately to Turbine. So the `awaitItem` is handled and dispatch is called. The issue is that that doesn't mean that `stateIn` has started collecting the upstream `state` yet and because StateFlow has a builtIn `distinctUntilChanged` there is also no way to wait for the actual first emission of `FlowReduxStateMachine`. There are a few solutions for this:
- use `state` instead of `stateFlow` in tests, that way the first emission for awaitItem comes from FlowReduxStateMachine and the `on`/`dispatch` is guaranteed to work
- replace `StateFlow` with `SharedFlow` by using `shareIn(..., replay = 1)`, similar to the above but lets you use the shared flow for tests so that the test is closer to a real consumer
- have a different initial state for the StateFlow and the StateMachine, probably not a nice solution

I would also generally recommend one of the first 2 in tests. `StateFlow` has some things like conflation of values that can easily make tests flaky since you might not get in between emissions sometimes.

**Comment by JBokMan** [comment]
Thank you so much!

We chose the second solution. In the example code the change is just from
```kotlin
val stateFlow: StateFlow<MachineState> = state.stateIn(
    scope = CoroutineScope(Dispatchers.Default),
    started = SharingStarted.Eagerly,
    initialValue = initialState
)
```
to
```kotlin
val stateFlow: SharedFlow<MachineState> = state.shareIn(
    scope = CoroutineScope(Dispatchers.Default),
    started = SharingStarted.Eagerly,
    replay = 1
)
```
