### ISSUE TITLE
Crash on setState

### ISSUE THREAD

**Issue by TillSimon** [freeletics/FlowRedux#86]
I'm seeing a crash when doing the following, but couldn't wrap my head around what's causing it:

```kotlin
collectWhileInAnyState(UserStore.stream()) { userState, getState, setState ->
    setState {
        when (userState) {
            UserState.LoggedOut -> LoadModel.LoggedOut
            is UserState.LoggedIn -> LoadModel.LoggedIn(userState.user.name)
        }
    }
}
```

Crash:
```
java.lang.IllegalStateException: ReceiveChannel.consumeAsFlow can be collected just once
        at kotlinx.coroutines.flow.ConsumeAsFlow.markConsumed(Channels.kt:100)
        at kotlinx.coroutines.flow.ConsumeAsFlow.collect(Channels.kt:123)
        at com.freeletics.flowredux.dsl.DslKt$reduxStore$$inlined$map$1.collect(SafeCollector.kt:127)
        at kotlinx.coroutines.flow.FlowKt__EmittersKt$onStart$$inlined$unsafeFlow$1.collect(SafeCollector.kt:127)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:135)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:102)
        at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
        at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:298)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:128)
        at kotlinx.coroutines.channels.AbstractChannel$ReceiveSelect.completeResumeReceive(AbstractChannel.kt:942)
        at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:79)
        at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:147)
        at kotlinx.coroutines.channels.ChannelCoroutine.send$suspendImpl(Unknown Source:2)
        at kotlinx.coroutines.channels.ChannelCoroutine.send(Unknown Source:0)
        at kotlinx.coroutines.flow.internal.SendingCollector.emit(SendingCollector.kt:19)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:33)
        at com.freeletics.flowredux.dsl.StoreWideCollectBuilderBlock$setStateFlow$2$setState$2.invokeSuspend(StoreWideCollectBuilderBlock.kt:43)
        at com.freeletics.flowredux.dsl.StoreWideCollectBuilderBlock$setStateFlow$2$setState$2.invoke(Unknown Source:14)
        at com.freeletics.flowredux.dsl.SetStateImpl.invoke(SetState.kt:51)
        at com.freeletics.flowredux.dsl.SetState.invoke$default(SetState.kt:34)
```
refer to [this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/1340) that discussed the introduction of `consumeAsFlow `

**Comment by TillSimon** [comment]
I was mislead by the stacktrace. It originated from the `state: Flow<S>` which can be collected just once. I was subscribing to a second state machine in `collectWhileInState(fsm2.state)` and when switching away and back to this state it tried to collect the exact same state flow for the second time, which it is not allowed to do.
